/**
 * Randomness for real cryptographic operations. There is exactly one source,
 * and no fallback.
 *
 * FIPS 204 §3.6.1 requires the 256-bit key-generation seed ξ to be "a fresh
 * (i.e. not previously used) random value generated using an approved RBG", and
 * the `rnd` of the default hedged signing variant to be generated by an RBG as
 * a side-channel and fault countermeasure. In a browser the only credible
 * source is `crypto.getRandomValues`.
 *
 * What this module exists to make impossible is the fallback. `Math.random` is
 * a non-cryptographic PRNG seeded from ambient state; a key generated from it
 * is guessable, and a signature made under it can leak the private key through
 * the very rejection loop that is supposed to protect it. A fallback is worse
 * than an error, because an error stops and a fallback ships.
 *
 * So when `crypto.getRandomValues` is unavailable this throws
 * `InsecureRandomnessError` and the operation does not happen. The UI catches
 * it and says so; it does not degrade, retry or substitute.
 *
 * `Math.random` DOES appear once in this codebase — in
 * `src/ui/fiat-shamir-viz.ts`, a deliberately reduced teaching model that
 * computes toy polynomials over a 257-element ring and is labelled as such
 * wherever it renders. `src/__tests__/runtime.test.ts` asserts it appears
 * nowhere else, and in particular nowhere under `src/crypto/`.
 */

/** Thrown when no cryptographically secure randomness is available. */
export class InsecureRandomnessError extends Error {
  constructor(detail: string) {
    super(
      `Secure randomness is unavailable: ${detail}. ` +
        'Key generation and signing have been stopped rather than fall back to a ' +
        'non-cryptographic source. This page requires the Web Crypto API ' +
        '(crypto.getRandomValues), which every current browser provides over HTTPS.'
    );
    this.name = 'InsecureRandomnessError';
  }
}

/**
 * Whether secure randomness is usable right now.
 *
 * Presence is not enough: the function can exist and throw (a hardened or
 * stubbed environment), so this calls it. A `QuotaExceededError` for a large
 * request would be a different failure, hence the deliberately small probe.
 */
export function secureRandomnessAvailable(): boolean {
  try {
    const c = globalThis.crypto as Crypto | undefined;
    if (!c || typeof c.getRandomValues !== 'function') return false;
    c.getRandomValues(new Uint8Array(1));
    return true;
  } catch {
    return false;
  }
}

/**
 * `length` cryptographically secure random bytes, or an exception.
 *
 * Never returns a partially-random or deterministic buffer. Note the check that
 * the output is not all zeros: `getRandomValues` is required to fill the array,
 * and a stub that silently no-ops would otherwise hand back a 32-byte seed of
 * zeros that keygen would accept without complaint. The false-positive rate for
 * genuine randomness at 32 bytes is 2^-256.
 */
export function secureRandomBytes(length: number): Uint8Array {
  const c = globalThis.crypto as Crypto | undefined;
  if (!c) throw new InsecureRandomnessError('globalThis.crypto is not defined');
  if (typeof c.getRandomValues !== 'function') {
    throw new InsecureRandomnessError('crypto.getRandomValues is not a function');
  }

  const out = new Uint8Array(length);
  try {
    c.getRandomValues(out);
  } catch (err) {
    throw new InsecureRandomnessError(
      `crypto.getRandomValues threw (${err instanceof Error ? err.message : String(err)})`
    );
  }

  if (length > 0 && out.every((b) => b === 0)) {
    throw new InsecureRandomnessError(
      `crypto.getRandomValues returned ${length} zero bytes, which indicates a stub rather than an RBG`
    );
  }
  return out;
}

/**
 * Stop before a real cryptographic operation if randomness is unavailable.
 *
 * Called by key generation and by signing. Verification deliberately does not
 * call it: verifying needs no randomness, and a reader whose browser cannot
 * generate keys should still be able to check a signature.
 */
export function requireSecureRandomness(operation: string): void {
  if (!secureRandomnessAvailable()) {
    throw new InsecureRandomnessError(`${operation} requires an RBG and none is available`);
  }
}
